# docker-compose.yml
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      # Database connection details
      - DB_HOST=db
      - DB_NAME=fitnesshub_db
      - DB_USER=fitnesshub_user
      - DB_PASS=supersecretpassword
    command: >
      sh -c "gunicorn fitnesshub.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      # Persists database data across container restarts
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=fitnesshub_db
      - POSTGRES_USER=fitnesshub_user
      - POSTGRES_PASSWORD=supersecretpassword
volumes:
  postgres_data: