services:
  app:
    build:
      context: .
    container_name: fitnesshub-app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: fitnesshub_db
      DB_USER: fitnesshub_user
      DB_PASS: supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: fitnesshub-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: fitnesshub_db
      POSTGRES_USER: fitnesshub_user
      POSTGRES_PASSWORD: supersecretpassword

volumes:
  postgres_data:
